package segments

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"sega2asm/disasm/m68k"
	"sega2asm/disasm/z80"
	"sega2asm/types"
	"sega2asm/types/code"
)

func init() {
	Register("m68k", processM68K)
	Register("z80", processZ80)
}

func processM68K(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}

	seg := ctx.Seg
	start := ctx.Start()
	end := ctx.End()
	labels := ctx.Labels
	if labels == nil {
		labels = types.NewLabels()
	}
	heur := true
	var baseRegs map[uint16]uint32
	var structRegs map[uint16]map[int32]string
	if ctx.Config != nil {
		heur = ctx.Config.HeuristicsEnabled(seg)
		baseRegs = ctx.Config.SegmentBaseRegs(seg)
		structRegs = ctx.Config.SegmentStructRegs(seg)
	}
	segEnd := seg
	segEnd.End = types.HexInt(end)
	items := disasmM68KSegment(ctx.ROM.Data, segEnd, m68k.BlockOptions{
		Labels:     labels.ByAddr,
		ImmLabels:  labels.Imm,
		BaseRegs:   baseRegs,
		StructRegs: structRegs,
		Heuristics: heur,
	})

	// Resolve VDP ctrl symbol name.
	vdpCtrlSym := m68k.HWPortName(0xC00004)
	if n, ok := labels.Get(0xC00004); ok {
		vdpCtrlSym = n
	}
	vdp := code.NewVDPAnnotator(vdpCtrlSym)
	env := code.HintEnv{
		ROM:     ctx.ROM.Data,
		Charmap: ctx.Charmap,
		Labels:  labels,
		BinDir:  filepath.Dir(outPath),
		Rel:     ctx.RelPath,
	}

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Segment: %s  $%06X–$%06X\n", seg.Name, start, end))
	if seg.Description != "" {
		sb.WriteString("; " + seg.Description + "\n")
	}
	sb.WriteString(fmt.Sprintf("\n\torg\t$%06X\n", start))

	labelHits := 0
	var results []m68k.Result
	for _, it := range items {
		if def := labels.Def(it.Addr); def != "" {
			if labels.Kind[it.Addr] == types.LabelUser {
				labelHits++
			}
			sb.WriteString("\n" + def)
		}
		if it.Hint != nil {
			h := *it.Hint
			h.Label = "" // emitted from the global label table above
			code.EmitHint(&sb, h, it.Addr, env)
			continue
		}
		results = append(results, *it.Res)
		sb.WriteString(withAddr(vdp.Annotate(it.Res.Text), it.Addr))
		sb.WriteByte('\n')
	}

	var splitHints []string
	if heur {
		splitHints = code.SuggestM68KSplits(results, seg, ctx.Syms, ctx.ROM.Data)
	}

	return &Result{
		Includes:  []Include{{Path: outPath}},
		Hints:     splitHints,
		LabelHits: labelHits,
	}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}

// withAddr appends the ROM address of an instruction as a trailing comment,
// aligned to a fixed column for readability.
func withAddr(text string, addr uint32) string {
	if strings.Contains(text, ";") {
		return fmt.Sprintf("%s [$%06X]", text, addr)
	}
	width := 0
	for _, c := range text {
		if c == '\t' {
			width = (width/8 + 1) * 8
		} else {
			width++
		}
	}
	pad := ""
	for width < 48 {
		pad += "\t"
		width = (width/8 + 1) * 8
	}
	if pad == "" {
		pad = "\t"
	}
	return fmt.Sprintf("%s%s; $%06X", text, pad, addr)
}

func processZ80(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}

	start := ctx.Start()
	data := ctx.ROMData()
	syms := ctx.Syms

	z80Org := uint32(ctx.Seg.Z80Org)
	results := z80.DisassembleBlock(data, 0, z80Org, uint32(len(data)), syms.ByAddr)

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Z80 Segment: %s  ROM:$%06X–$%06X\n\n", ctx.Seg.Name, start, ctx.End()))
	sb.WriteString(fmt.Sprintf("\torg\t$%04X\n\n", z80Org))

	labelHits := 0
	for _, res := range results {
		addr := res.Addr
		if syms.Has(addr) {
			labelHits++
			ctx.Logv("  [label] %s = $%04X", syms.Label(addr), addr)
			sb.WriteByte('\n')
			sb.WriteString(syms.Label(addr) + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else if addr == z80Org && ctx.Seg.Name != "" {
			sb.WriteByte('\n')
			sb.WriteString(ctx.Seg.Name + ":")
			sb.WriteString(fmt.Sprintf("\t\t\t\t; $%04X\n", addr))
		} else {
			sb.WriteString(fmt.Sprintf("; $%04X\n", addr))
		}
		sb.WriteString(res.Text)
		sb.WriteByte('\n')
	}

	if len(ctx.ExtraBins) > 0 {
		sb.WriteString("\n; Embedded data\n")
		for _, e := range ctx.ExtraBins {
			sb.WriteString(fmt.Sprintf("\tincbin\t'%s'\n", filepath.ToSlash(e.Path)))
		}
	}

	return &Result{
		Includes:  []Include{{Path: outPath}},
		LabelHits: labelHits,
	}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}
