package segments

import (
	"fmt"
	"os"
	"strings"

	"sega2asm/types/code"
)

func init() {
	Register("data", processData)
}

// processData emits a block of data as dc.b / dc.w / dc.l directives with a
// label at every referenced address inside it. Use it for tables and other
// structured data that code points into; use bin for large opaque blobs.
//
//	format: byte | word | long | text   (default: word if start is even)
func processData(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}
	start, end := ctx.Start(), ctx.End()
	unit := 2
	strs := false
	switch strings.ToLower(ctx.Seg.Format) {
	case "byte", "b":
		unit = 1
	case "long", "l":
		unit = 4
	case "text":
		unit, strs = 1, true
	}
	if start&1 != 0 {
		unit = 1
	}

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Data: %s  $%06X–$%06X\n", ctx.Seg.Name, start, end))
	if ctx.Seg.Description != "" {
		sb.WriteString("; " + ctx.Seg.Description + "\n")
	}
	sb.WriteString(fmt.Sprintf("\n\torg\t$%06X\n", start))
	if name, ok := ctx.Labels.Get(start); ok {
		sb.WriteString(name + ":\n")
	}
	code.WriteData(&sb, ctx.ROM.Data, start, end, unit, ctx.Labels, strs)
	return &Result{Includes: []Include{{Path: outPath}}}, os.WriteFile(outPath, []byte(sb.String()), 0644)
}
