package segments

import (
	"fmt"
	"os"
	"strings"

	"sega2asm/types"
	"sega2asm/types/code"
)

func init() {
	Register("table", processTable)
}

// tableEntrySize returns 4 for long tables and 2 for word tables.
func tableEntrySize(seg types.Segment) uint32 {
	if strings.HasPrefix(strings.ToLower(seg.Format), "w") {
		return 2
	}
	return 4
}

func tableBase(seg types.Segment) uint32 {
	if seg.Base != 0 {
		return uint32(seg.Base)
	}
	return uint32(seg.Start)
}

// tableTargets returns the ROM addresses referenced by a table segment.
func tableTargets(rom []byte, seg types.Segment) []uint32 {
	n := tableEntrySize(seg)
	start, end := uint32(seg.Start), uint32(seg.End)
	if int(end) > len(rom) {
		end = uint32(len(rom))
	}
	var out []uint32
	for a := start; a+n <= end; a += n {
		out = append(out, tableTarget(rom, seg, a))
	}
	return out
}

func tableTarget(rom []byte, seg types.Segment, a uint32) uint32 {
	var v uint32
	if tableEntrySize(seg) == 2 {
		v = uint32(be16(rom, a))
		if seg.Relative {
			if seg.Signed {
				v = uint32(int32(tableBase(seg)) + int32(int16(v)))
			} else {
				v += tableBase(seg)
			}
		}
	} else {
		v = be32(rom, a)
		if seg.Relative {
			v += tableBase(seg)
		}
	}
	return v
}

// processTable emits a pointer / offset table as assembly. Entries whose
// target has a label are written symbolically (dc.l label or
// dc.w label-base), so the data stays correct if the targets move.
//
//	format:   long | word
//	relative: entries are offsets from base (default: the table start)
//	signed:   word offsets are sign-extended (jump tables); default unsigned
func processTable(ctx *Context) (*Result, error) {
	outPath := ctx.SegPath(ctx.AsmDir, ".asm")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: outPath}}}, nil
	}
	if err := ctx.EnsureDir(outPath); err != nil {
		return nil, err
	}
	seg := ctx.Seg
	rom := ctx.ROM.Data
	start, end := ctx.Start(), ctx.End()
	n := tableEntrySize(seg)
	base := tableBase(seg)
	baseName, haveBase := ctx.Labels.Get(base)

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Table: %s  $%06X–$%06X (%s, %d entries)\n", seg.Name, start, end,
		map[bool]string{true: "relative", false: "absolute"}[seg.Relative], (end-start)/n))
	if seg.Description != "" {
		sb.WriteString("; " + seg.Description + "\n")
	}
	sb.WriteString(fmt.Sprintf("\n\torg\t$%06X\n\n", start))
	sb.WriteString(ctx.Labels.Def(start))
	hits := 0
	a := start
	for ; a+n <= end; a += n {
		if a != start {
			sb.WriteString(ctx.Labels.Def(a))
		}
		t := tableTarget(rom, seg, a)
		tn, ok := ctx.Labels.Get(t)
		switch {
		case n == 4 && !seg.Relative && ok:
			sb.WriteString(fmt.Sprintf("\tdc.l\t%s\n", tn))
			hits++
		case n == 4 && seg.Relative && ok && haveBase:
			sb.WriteString(fmt.Sprintf("\tdc.l\t%s-%s\n", tn, baseName))
			hits++
		case n == 2 && seg.Relative && ok && haveBase:
			sb.WriteString(fmt.Sprintf("\tdc.w\t%s-%s\n", tn, baseName))
			hits++
		case n == 2 && !seg.Relative && ok && t < 0x8000:
			sb.WriteString(fmt.Sprintf("\tdc.w\t%s\n", tn))
			hits++
		case n == 4:
			sb.WriteString(fmt.Sprintf("\tdc.l\t$%08X\n", be32(rom, a)))
		default:
			sb.WriteString(fmt.Sprintf("\tdc.w\t$%04X\n", be16(rom, a)))
		}
	}
	code.WriteDCB(&sb, rom[a:end], 16, false)
	return &Result{Includes: []Include{{Path: outPath}}, LabelHits: hits},
		os.WriteFile(outPath, []byte(sb.String()), 0644)
}
