package segments

import (
	"fmt"
	"os"
	"strings"

	"sega2asm/types/code"
)

func init() {
	Register("text", processText)
}

// processText emits a text block as byte-exact dc.b directives (printable
// runs as strings, the charmap decoding as comments) plus a decoded .txt
// reference file.
func processText(ctx *Context) (*Result, error) {
	asmPath := ctx.SegPath(ctx.AsmDir, ".asm")
	txtPath := ctx.SegPath(ctx.AssetDir, ".txt")
	if ctx.DryRun {
		return &Result{Includes: []Include{{Path: asmPath}}}, nil
	}
	if err := ctx.EnsureDir(asmPath); err != nil {
		return nil, err
	}
	if err := ctx.EnsureDir(txtPath); err != nil {
		return nil, err
	}

	data := ctx.ROMData()
	var decoded string
	if !ctx.Charmap.Empty() {
		decoded = ctx.Charmap.DecodeAll(data)
	} else {
		decoded = strings.Map(func(r rune) rune {
			if r >= 0x20 && r < 0x7F {
				return r
			}
			return '.'
		}, string(data))
	}
	if err := os.WriteFile(txtPath, []byte(decoded), 0644); err != nil {
		return nil, err
	}

	var sb strings.Builder
	sb.WriteString("; Auto-generated by sega2asm\n")
	sb.WriteString(fmt.Sprintf("; Text: %s  $%06X–$%06X\n", ctx.Seg.Name, ctx.Start(), ctx.End()))
	sb.WriteString(fmt.Sprintf("\n\torg\t$%06X\n", ctx.Start()))
	if name, ok := ctx.Labels.Get(ctx.Start()); ok {
		sb.WriteString(name + ":\n")
	}
	code.WriteData(&sb, ctx.ROM.Data, ctx.Start(), ctx.End(), 1, ctx.Labels, true)
	return &Result{Includes: []Include{{Path: asmPath}}}, os.WriteFile(asmPath, []byte(sb.String()), 0644)
}
